spring:
  jpa:
    generate-ddl: 'false'
    database: postgresql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        search:
          backend:
            analysis:
              configurer: ru.clevertec.comment.search.LuceneConfig
            directory:
              root: src\main\resources\db\index
  datasource:
    password: admin
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5433/nms_comment_service
  main:
    allow-circular-references: true
  application:
    name: comment-service
server:
  port: 8085
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        SQL: DEBUG
aop:
  logging:
    enabled: true

exception:
  handling:
    enabled: true
